### ISSUE TITLE
Face recognition 

### ISSUE THREAD

**Issue by Judoguy12** [mrpjevans/smartdoor#1]
Hi just wondering where face recognition is as magpi says it is in this repo

Thanks

**Comment by pjnorth27** [comment]
Hi, I sadly didn't get time over the festive break to address all of this. Here's the repo I tested (with great success!) https://github.com/ageitgey/face_recognition

**Comment by mrpjevans** [comment]
Hi, I sadly didn't get time over the festive break to address all of this. Here's the repo I tested (with great success!) https://github.com/ageitgey/face_recognition

**Comment by Judoguy12** [comment]
Ok thanks, will it be up eventually? Dont worry if not i am just worndering

**Comment by pjnorth27** [comment]
Yes, absolutely, life is just getting in the way! :)

**Comment by Judoguy12** [comment]
Ok Thanks.

Life is Busy.
